case_id: '1'
party_role: plaintiff
dataset_path: case_data_extracted.json
case_type: 侵犯公民人身权利、民主权利罪
case_category: criminal
case_state: 空闲
designated_lawyer_id: ''
assigned_lawyer_id: ''
profile: {}
source_title: 甲过失致人死亡案
