"""Categorized tool exports for the SimLaw backend — 纯刑事。"""

from .client import (
    create_save_client_memory_tool,
)
from .common import (
    ArtifactReader,
    LawRetrievalTool,
    create_law_retrieval_tool,
    create_law_search_function,
    load_agent_skills,
    normalize_skill_dirs,
)
from .legal import (
    # 通用
    BENCHMARK_EVAL_TOOL_NAME,
    CASE_RETRIEVAL_TOOL_NAME,
    CITATION_CHECK_TOOL_NAME,
    DOCUMENT_COMPARE_TOOL_NAME,
    LocalCaseRetrievalEngine,
    BenchmarkEvalTool,
    CitationCheckTool,
    DocumentCompareTool,
    create_benchmark_eval_tool,
    create_case_retrieval_tool,
    create_case_search_function,
    create_citation_check_tool,
    create_document_drafting_tool_for_scenario,
    create_document_compare_tool,
    create_judgment_document_tool_for_scenario,
    create_save_lawyer_memory_tool,
    # 元典法条/案例检索
    create_yuandian_case_tool,
    create_yuandian_law_tool,
    search_yuandian_case,
    search_yuandian_law,
    # 刑事
    IndictmentDraftingTool,
    DefenseOpinionDraftingTool,
    PublicProsecutionTool,
    CriminalFirstInstanceJudgmentDraftingTool,
    CriminalSecondInstanceJudgmentDraftingTool,
    create_indictment_drafting_tool,
    create_defense_opinion_drafting_tool,
    create_public_prosecution_drafting_tool,
    create_first_instance_criminal_judgment_drafting_tool,
    create_second_instance_criminal_judgment_drafting_tool,
)

__all__ = [
    "ArtifactReader",
    "BENCHMARK_EVAL_TOOL_NAME",
    "CASE_RETRIEVAL_TOOL_NAME",
    "CITATION_CHECK_TOOL_NAME",
    "DOCUMENT_COMPARE_TOOL_NAME",
    "LawRetrievalTool",
    "LocalCaseRetrievalEngine",
    "BenchmarkEvalTool",
    "CitationCheckTool",
    "DocumentCompareTool",
    "create_benchmark_eval_tool",
    "create_case_retrieval_tool",
    "create_case_search_function",
    "create_citation_check_tool",
    "create_document_drafting_tool_for_scenario",
    "create_document_compare_tool",
    "create_judgment_document_tool_for_scenario",
    "create_law_retrieval_tool",
    "create_law_search_function",
    "create_save_client_memory_tool",
    "create_save_lawyer_memory_tool",
    # 元典法条/案例检索
    "create_yuandian_case_tool",
    "create_yuandian_law_tool",
    "search_yuandian_case",
    "search_yuandian_law",
    "load_agent_skills",
    "normalize_skill_dirs",
    # 刑事
    "IndictmentDraftingTool",
    "DefenseOpinionDraftingTool",
    "PublicProsecutionTool",
    "CriminalFirstInstanceJudgmentDraftingTool",
    "CriminalSecondInstanceJudgmentDraftingTool",
    "create_indictment_drafting_tool",
    "create_defense_opinion_drafting_tool",
    "create_public_prosecution_drafting_tool",
    "create_first_instance_criminal_judgment_drafting_tool",
    "create_second_instance_criminal_judgment_drafting_tool",
]
